version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ENVIRONMENT=development
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=destack_transport
      - DB_SSLMODE=disable
      - JWT_SECRET=desenvolvimento-secreto-temporario
      - JWT_EXPIRES_IN=24
    volumes:
      - ./logs:/root/logs

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=destack_transport
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: